DLXSimulator079:
	g++ -c main.cpp memory.cpp register.cpp instruction.cpp preprocess.cpp
	g++ -O3 -o DLXSimulator079 main.o memory.o register.o instruction.o preprocess.o
	
clean :
	rm DLXSimulator079 main.o memory.o register.o instruction.o preprocess.o
